// ============================================================================
// Iron Protocol - Intelligence Report System
// Manages intelligence reports generated from espionage activities and
// presented to the player for strategic decision-making.
// ============================================================================

using System;
using System.Collections.Generic;
using System.Linq;
using UnityEngine;
using IronProtocol.HexMap;
using IronProtocol.Espionage;

namespace IronProtocol.Espionage
{
    // ========================================================================
    // INTEL REPORT DATA CLASS
    // ========================================================================

    /// <summary>
    /// Represents a single intelligence report generated by spy networks,
    /// reconnaissance missions, or diplomatic channels. Reports are categorized
    /// by type and carry a confidence level reflecting their reliability.
    /// </summary>
    [Serializable]
    public class IntelReport
    {
        /// <summary>Unique identifier for this intelligence report.</summary>
        public string ReportId { get; set; }

        /// <summary>Short title summarizing the report's content.</summary>
        public string Title { get; set; }

        /// <summary>Detailed narrative description of the intelligence findings.</summary>
        public string Description { get; set; }

        /// <summary>The nation that sourced this intelligence (the spy owner).</summary>
        public string SourceNation { get; set; }

        /// <summary>The nation that this report is about (the intelligence target).</summary>
        public string TargetNation { get; set; }

        /// <summary>The game turn number on which this report was generated.</summary>
        public int TurnNumber { get; set; }

        /// <summary>
        /// The reliability and depth of the intelligence in this report.
        /// Higher confidence levels mean more accurate and actionable information.
        /// </summary>
        public IntelLevel Confidence { get; set; }

        /// <summary>
        /// A list of specific intelligence findings (unit counts, resource estimates, etc.).
        /// </summary>
        public List<string> Details { get; set; } = new List<string>();

        /// <summary>Whether the player has already read and acknowledged this report.</summary>
        public bool IsRead { get; set; }

        /// <summary>The category/type of intelligence this report covers.</summary>
        public IntelReportCategory Category { get; set; }

        /// <summary>Timestamp of when the report was generated (real-time).</summary>
        public DateTime GeneratedAt { get; set; }

        /// <summary>
        /// Initializes a new intelligence report with the specified metadata.
        /// </summary>
        /// <param name="reportId">Unique identifier.</param>
        /// <param name="title">Report title.</param>
        /// <param name="sourceNation">The nation that produced the report.</param>
        /// <param name="targetNation">The nation the report is about.</param>
        /// <param name="turnNumber">Current game turn.</param>
        public IntelReport(string reportId, string title, string sourceNation,
                           string targetNation, int turnNumber)
        {
            ReportId = reportId;
            Title = title;
            Description = string.Empty;
            SourceNation = sourceNation;
            TargetNation = targetNation;
            TurnNumber = turnNumber;
            Confidence = IntelLevel.None;
            Details = new List<string>();
            IsRead = false;
            Category = IntelReportCategory.General;
            GeneratedAt = DateTime.UtcNow;
        }

        /// <summary>
        /// Returns a formatted summary string suitable for display in UI lists.
        /// </summary>
        public string GetSummary()
        {
            string readMarker = IsRead ? "[READ]" : "[NEW]";
            return $"{readMarker} Turn {TurnNumber}: {Title} (Confidence: {Confidence})";
        }
    }

    /// <summary>
    /// Categorizes the type of intelligence contained in a report.
    /// Used for filtering and prioritizing reports in the UI.
    /// </summary>
    public enum IntelReportCategory
    {
        /// <summary>Military forces, deployments, and movements.</summary>
        Military,

        /// <summary>Economic resources, production, and trade.</summary>
        Economic,

        /// <summary>Technology research progress and capabilities.</summary>
        Technology,

        /// <summary>Diplomatic relations, agreements, and intentions.</summary>
        Diplomatic,

        /// <summary>General or multi-category intelligence.</summary>
        General
    }

    // ========================================================================
    // INTEL REPORT MANAGER (MONOBEHAVIOUR)
    // ========================================================================

    /// <summary>
    /// Manages the generation, storage, and retrieval of intelligence reports.
    /// Auto-generates reports from active spy networks and completed missions,
    /// and provides filtered access for UI display.
    /// 
    /// <para>Usage:</para>
    /// <list type="bullet">
    ///   <item>Call <see cref="GenerateAutoReports"/> each turn to produce reports from spy activity.</item>
    ///   <item>Use <see cref="GetUnreadReports"/> to populate the player's intel inbox.</item>
    ///   <item>Subscribe to <see cref="OnNewReportGenerated"/> for real-time notifications.</item>
    /// </list>
    /// </summary>
    public class IntelReportManager : MonoBehaviour
    {
        // --------------------------------------------------------------------
        // INSPECTOR CONFIGURATION
        // --------------------------------------------------------------------

        [Header("Report Generation")]
        [Tooltip("Maximum number of reports to generate per nation per turn from auto-generation.")]
        [SerializeField] private int maxAutoReportsPerTurn = 3;

        [Tooltip("Minimum turns between economic reports for the same target.")]
        [SerializeField] private int economicReportCooldown = 4;

        [Tooltip("Minimum turns between tech reports for the same target.")]
        [SerializeField] private int techReportCooldown = 6;

        [Tooltip("Minimum turns between military reports for the same target.")]
        [SerializeField] private int militaryReportCooldown = 2;

        [Header("Report Limits")]
        [Tooltip("Maximum total reports stored before oldest are archived.")]
        [SerializeField] private int maxStoredReports = 100;

        [Tooltip("Probability per turn of generating a report from each installed network (0-1).")]
        [SerializeField] [Range(0f, 1f)] private float networkReportChance = 0.4f;

        // --------------------------------------------------------------------
        // PRIVATE STATE
        // --------------------------------------------------------------------

        /// <summary>All generated reports, keyed by report ID.</summary>
        private readonly Dictionary<string, IntelReport> _reports = new Dictionary<string, IntelReport>();

        /// <summary>
        /// Reports organized by the receiving nation, for quick lookup.
        /// Key: receiving nation ID, Value: list of report IDs.
        /// </summary>
        private readonly Dictionary<string, List<string>> _reportsByNation = new Dictionary<string, List<string>>();

        /// <summary>
        /// Tracks the last turn a specific report type was generated for each target nation.
        /// Key: "nationId_category", Value: last turn number.
        /// </summary>
        private readonly Dictionary<string, int> _reportCooldowns = new Dictionary<string, int>();

        /// <summary>Running report ID counter for unique generation.</summary>
        private int _reportIdCounter;

        /// <summary>Reference to the EspionageManager for reading intel data.</summary>
        private EspionageManager _espionageManager;

        /// <summary>Reference to the HexGrid for terrain and position queries.</summary>
        private HexGrid _hexGrid;

        // --------------------------------------------------------------------
        // EVENTS
        // --------------------------------------------------------------------

        /// <summary>
        /// Fired when a new intelligence report is generated.
        /// Parameters: (report, receivingNationId).
        /// </summary>
        public event Action<IntelReport, string> OnNewReportGenerated;

        /// <summary>
        /// Fired when a report is marked as read by the player.
        /// </summary>
        public event Action<string> OnReportRead;

        // --------------------------------------------------------------------
        // UNITY LIFECYCLE
        // --------------------------------------------------------------------

        /// <summary>
        /// Resolves references to required game systems.
        /// </summary>
        private void Awake()
        {
            Debug.Log("[IntelReportManager] System initialized.");
        }

        /// <summary>
        /// Late initialization to find the EspionageManager and HexGrid after all systems are awake.
        /// </summary>
        private void Start()
        {
            _espionageManager = FindEspionageManager();
            _hexGrid = FindHexGrid();

            if (_espionageManager == null)
                Debug.LogWarning("[IntelReportManager] EspionageManager reference not found. Auto-reports will use fallback data.");
            if (_hexGrid == null)
                Debug.LogWarning("[IntelReportManager] HexGrid reference not found. Military reports will use simulated data.");
        }

        // ====================================================================
        // REPORT RETRIEVAL
        // ====================================================================

        /// <summary>
        /// Gets all unread intelligence reports for the specified nation.
        /// Reports are ordered by turn number (newest first).
        /// </summary>
        /// <param name="nationId">The nation to retrieve unread reports for.</param>
        /// <returns>List of unread IntelReport objects, newest first.</returns>
        public List<IntelReport> GetUnreadReports(string nationId)
        {
            if (!_reportsByNation.TryGetValue(nationId, out List<string> reportIds))
                return new List<IntelReport>();

            return reportIds
                .Where(id => _reports.TryGetValue(id, out IntelReport r) && !r.IsRead)
                .Select(id => _reports[id])
                .OrderByDescending(r => r.TurnNumber)
                .ToList();
        }

        /// <summary>
        /// Gets all reports for a nation, including read ones.
        /// </summary>
        /// <param name="nationId">The nation to retrieve reports for.</param>
        /// <returns>List of all IntelReport objects for the nation, newest first.</returns>
        public List<IntelReport> GetAllReports(string nationId)
        {
            if (!_reportsByNation.TryGetValue(nationId, out List<string> reportIds))
                return new List<IntelReport>();

            return reportIds
                .Where(id => _reports.ContainsKey(id))
                .Select(id => _reports[id])
                .OrderByDescending(r => r.TurnNumber)
                .ToList();
        }

        /// <summary>
        /// Gets reports filtered by category for a specific nation.
        /// </summary>
        /// <param name="nationId">The nation to retrieve reports for.</param>
        /// <param name="category">The report category to filter by.</param>
        /// <returns>Filtered list of reports matching the category.</returns>
        public List<IntelReport> GetReportsByCategory(string nationId, IntelReportCategory category)
        {
            return GetAllReports(nationId)
                .Where(r => r.Category == category)
                .ToList();
        }

        /// <summary>
        /// Gets reports targeting a specific nation.
        /// </summary>
        /// <param name="targetNation">The nation that the reports are about.</param>
        /// <returns>List of reports about the target nation.</returns>
        public List<IntelReport> GetReportsAboutNation(string targetNation)
        {
            return _reports.Values
                .Where(r => r.TargetNation == targetNation)
                .OrderByDescending(r => r.TurnNumber)
                .ToList();
        }

        /// <summary>
        /// Marks a report as read, removing it from the unread queue.
        /// </summary>
        /// <param name="reportId">The ID of the report to mark as read.</param>
        public void MarkReportRead(string reportId)
        {
            if (_reports.TryGetValue(reportId, out IntelReport report))
            {
                report.IsRead = true;
                Debug.Log($"[IntelReportManager] Report '{reportId}' marked as read.");
                OnReportRead?.Invoke(reportId);
            }
        }

        /// <summary>
        /// Marks all unread reports for a nation as read.
        /// </summary>
        /// <param name="nationId">The nation whose reports to mark as read.</param>
        public void MarkAllReportsRead(string nationId)
        {
            var unread = GetUnreadReports(nationId);
            foreach (var report in unread)
            {
                report.IsRead = true;
            }
            Debug.Log($"[IntelReportManager] Marked {unread.Count} reports as read for {nationId}.");
        }

        /// <summary>
        /// Gets the total count of unread reports across all nations.
        /// </summary>
        public int TotalUnreadCount
        {
            get { return _reports.Count(r => !r.Value.IsRead); }
        }

        // ====================================================================
        // AUTO-GENERATION
        // ====================================================================

        /// <summary>
        /// Automatically generates intelligence reports based on active spy networks
        /// and recent mission results. Should be called once per turn.
        /// </summary>
        /// <param name="nationId">The nation to generate reports for.</param>
        /// <param name="espionage">The EspionageManager containing current intel data.</param>
        public void GenerateAutoReports(string nationId, EspionageManager espionage)
        {
            if (espionage == null)
            {
                Debug.LogWarning("[IntelReportManager] Cannot generate reports: EspionageManager is null.");
                return;
            }

            _espionageManager = espionage;
            int reportsGenerated = 0;

            // Generate reports from installed spy networks
            var allSpies = espionage.GetAllSpies();
            if (allSpies.TryGetValue(nationId, out List<Spy> nationSpies))
            {
                foreach (Spy spy in nationSpies)
                {
                    if (spy.IsKilled || spy.IsCaptured || spy.TurnsRemaining > 0)
                        continue;

                    // Check if spy has an installed network in the assigned nation
                    NationIntel intel = espionage.GetIntelForNation(spy.AssignedNation);
                    if (intel.CounterEspionageLevel > 0.2f ||
                        intel.GetOverallIntelScore() > 0.1f)
                    {
                        // Generate a report based on available intel
                        if (reportsGenerated < maxAutoReportsPerTurn)
                        {
                            IntelReport report = GenerateReportFromIntel(nationId, spy.AssignedNation, intel);
                            if (report != null)
                            {
                                StoreReport(report, nationId);
                                reportsGenerated++;
                            }
                        }
                    }
                }
            }

            Debug.Log($"[IntelReportManager] Generated {reportsGenerated} auto-reports for {nationId}.");
        }

        // ====================================================================
        // SPECIALIZED REPORT GENERATORS
        // ====================================================================

        /// <summary>
        /// Generates a military intelligence report about the target nation,
        /// detailing known unit positions, force compositions, and deployments.
        /// </summary>
        /// <param name="targetNation">The nation to report on.</param>
        /// <param name="grid">The hex grid for position lookups.</param>
        /// <returns>A military IntelReport, or null if insufficient intel.</returns>
        public IntelReport GenerateMilitaryReport(string targetNation, HexGrid grid)
        {
            if (_espionageManager == null)
                return null;

            NationIntel intel = _espionageManager.GetIntelForNation(targetNation);
            if (intel.MilitaryIntel == IntelLevel.None)
                return null;

            string cooldownKey = $"{targetNation}_Military";
            int currentTurn = GetEstimatedTurnNumber();
            if (_reportCooldowns.TryGetValue(cooldownKey, out int lastTurn) && currentTurn - lastTurn < militaryReportCooldown)
                return null;

            _reportIdCounter++;
            IntelReport report = new IntelReport(
                $"RPT_MIL_{_reportIdCounter:D4}",
                $"Military Intelligence: {targetNation}",
                "Intelligence Agency",
                targetNation,
                currentTurn
            )
            {
                Category = IntelReportCategory.Military,
                Confidence = intel.MilitaryIntel
            };

            // Generate findings based on intel level
            switch (intel.MilitaryIntel)
            {
                case IntelLevel.Low:
                    report.Description = $"Limited military intelligence on {targetNation}. " +
                                        "General force disposition is vaguely known.";
                    report.Details.Add("Approximate military strength estimated.");
                    report.Details.Add("Major troop concentrations identified in 1-2 regions.");
                    int lowUnitCount = UnityEngine.Random.Range(3, 8);
                    report.Details.Add($"Estimated {lowUnitCount} military units in the field.");
                    break;

                case IntelLevel.Medium:
                    report.Description = $"Moderate military intelligence on {targetNation}. " +
                                        "Force composition and general deployment patterns are known.";
                    report.Details.Add("Infantry, armor, and support unit distribution mapped.");
                    report.Details.Add("Primary staging areas identified.");
                    int medUnits = UnityEngine.Random.Range(5, 15);
                    report.Details.Add($"Estimated {medUnits} military units confirmed or suspected.");
                    report.Details.Add($"Air defense capabilities: {UnityEngine.Random.Range(1, 4)} sites detected.");
                    break;

                case IntelLevel.High:
                    report.Description = $"Detailed military intelligence on {targetNation}. " +
                                        "Unit types, positions, and readiness levels are well-documented.";
                    report.Details.Add("Complete order of battle partially reconstructed.");
                    report.Details.Add("Unit readiness and supply status estimated.");
                    int highUnits = UnityEngine.Random.Range(10, 25);
                    report.Details.Add($"{highUnits} units tracked with position data.");
                    report.Details.Add("Reserve forces and reinforcement routes identified.");
                    report.Details.Add($"Expected troop strength: ~{UnityEngine.Random.Range(15000, 50000)} personnel.");
                    break;

                case IntelLevel.Complete:
                    report.Description = $"Comprehensive military intelligence on {targetNation}. " +
                                        "Full situational awareness achieved. Real-time tracking possible.";
                    report.Details.Add("Complete order of battle reconstructed.");
                    report.Details.Add("Command structure identified.");
                    report.Details.Add("Supply lines, depots, and logistics network mapped.");
                    report.Details.Add("Communication protocols intercepted.");
                    int totalUnits = UnityEngine.Random.Range(20, 40);
                    report.Details.Add($"{totalUnits} units with precise positions and composition data.");
                    report.Details.Add($"Exact troop strength: {UnityEngine.Random.Range(30000, 80000)} personnel.");
                    report.Details.Add("War plans and contingency operations partially decoded.");
                    break;
            }

            // Add known unit positions from intel
            if (intel.KnownUnitPositions.Count > 0)
            {
                report.Details.Add($"Tracking {intel.KnownUnitPositions.Count} confirmed unit positions:");
                int displayLimit = Mathf.Min(intel.KnownUnitPositions.Count, 5);
                int count = 0;
                foreach (var unitPos in intel.KnownUnitPositions.OrderByDescending(kvp => kvp.Value))
                {
                    if (count >= displayLimit) break;
                    report.Details.Add($"  - {unitPos.Key} (confidence: {unitPos.Value:P0})");
                    count++;
                }
                if (intel.KnownUnitPositions.Count > displayLimit)
                {
                    report.Details.Add($"  ... and {intel.KnownUnitPositions.Count - displayLimit} more.");
                }
            }

            _reportCooldowns[cooldownKey] = currentTurn;
            return report;
        }

        /// <summary>
        /// Generates an economic intelligence report about the target nation,
        /// detailing resource stockpiles, production capacity, and trade activities.
        /// </summary>
        /// <param name="targetNation">The nation to report on.</param>
        /// <returns>An economic IntelReport, or null if insufficient intel.</returns>
        public IntelReport GenerateEconomicReport(string targetNation)
        {
            if (_espionageManager == null)
                return null;

            NationIntel intel = _espionageManager.GetIntelForNation(targetNation);
            if (intel.EconomicIntel == IntelLevel.None)
                return null;

            string cooldownKey = $"{targetNation}_Economic";
            int currentTurn = GetEstimatedTurnNumber();
            if (_reportCooldowns.TryGetValue(cooldownKey, out int lastTurn) && currentTurn - lastTurn < economicReportCooldown)
                return null;

            _reportIdCounter++;
            IntelReport report = new IntelReport(
                $"RPT_ECO_{_reportIdCounter:D4}",
                $"Economic Intelligence: {targetNation}",
                "Intelligence Agency",
                targetNation,
                currentTurn
            )
            {
                Category = IntelReportCategory.Economic,
                Confidence = intel.EconomicIntel
            };

            // Generate findings based on economic intel level
            switch (intel.EconomicIntel)
            {
                case IntelLevel.Low:
                    report.Description = $"Basic economic intelligence on {targetNation}. " +
                                        "General economic health indicators available.";
                    string healthLow = GetRandomEconomicHealth();
                    report.Details.Add($"Overall economic health: {healthLow}.");
                    report.Details.Add($"Treasury estimated at approximately {UnityEngine.Random.Range(100, 1000)} gold.");
                    break;

                case IntelLevel.Medium:
                    report.Description = $"Moderate economic intelligence on {targetNation}. " +
                                        "Resource production and trade patterns identified.";
                    report.Details.Add($"Treasury estimated at {UnityEngine.Random.Range(500, 3000)} gold.");
                    report.Details.Add("Major resource production sites identified.");
                    string[] resources = { "Iron", "Food", "Oil", "Rare Minerals", "Timber" };
                    string primaryResource = resources[UnityEngine.Random.Range(0, resources.Length)];
                    report.Details.Add($"Primary export: {primaryResource}.");
                    report.Details.Add("Trade route efficiency rated as moderate.");
                    break;

                case IntelLevel.High:
                    report.Description = $"Detailed economic intelligence on {targetNation}. " +
                                        "Production rates, stockpiles, and trade agreements well-documented.";
                    report.Details.Add($"Treasury estimated at {UnityEngine.Random.Range(2000, 8000)} gold (high confidence).");
                    report.Details.Add("Complete resource production breakdown available.");
                    report.Details.Add("Trade agreements and dependencies mapped.");
                    report.Details.Add($"Industrial output: {UnityEngine.Random.Range(40, 90)}% of capacity.");
                    report.Details.Add($"Food reserves: {'Adequate' /* conditional */} estimated {UnityEngine.Random.Range(3, 12)} months supply.");
                    break;

                case IntelLevel.Complete:
                    report.Description = $"Complete economic intelligence on {targetNation}. " +
                                        "Full financial transparency achieved.";
                    report.Details.Add($"Treasury: {UnityEngine.Random.Range(5000, 15000)} gold (exact figure).");
                    report.Details.Add("All resource stockpiles quantified.");
                    report.Details.Add("Complete trade network mapped with volumes.");
                    report.Details.Add("Black market activity identified and estimated.");
                    report.Details.Add("Economic vulnerability assessment completed.");
                    report.Details.Add("Industrial production capacity: exact figures available.");
                    break;
            }

            _reportCooldowns[cooldownKey] = currentTurn;
            return report;
        }

        /// <summary>
        /// Generates a technology intelligence report about the target nation,
        /// detailing research progress, known technologies, and tech capabilities.
        /// </summary>
        /// <param name="targetNation">The nation to report on.</param>
        /// <returns>A technology IntelReport, or null if insufficient intel.</returns>
        public IntelReport GenerateTechReport(string targetNation)
        {
            if (_espionageManager == null)
                return null;

            NationIntel intel = _espionageManager.GetIntelForNation(targetNation);
            if (intel.TechIntel == IntelLevel.None)
                return null;

            string cooldownKey = $"{targetNation}_Technology";
            int currentTurn = GetEstimatedTurnNumber();
            if (_reportCooldowns.TryGetValue(cooldownKey, out int lastTurn) && currentTurn - lastTurn < techReportCooldown)
                return null;

            _reportIdCounter++;
            IntelReport report = new IntelReport(
                $"RPT_TECH_{_reportIdCounter:D4}",
                $"Technology Intelligence: {targetNation}",
                "Intelligence Agency",
                targetNation,
                currentTurn
            )
            {
                Category = IntelReportCategory.Technology,
                Confidence = intel.TechIntel
            };

            // Generate findings based on tech intel level
            switch (intel.TechIntel)
            {
                case IntelLevel.Low:
                    report.Description = $"Basic technology intelligence on {targetNation}. " +
                                        "General tech level estimated.";
                    string techEra = GetRandomTechEra();
                    report.Details.Add($"Estimated technological era: {techEra}.");
                    report.Details.Add("Specific research projects unknown.");
                    break;

                case IntelLevel.Medium:
                    report.Description = $"Moderate technology intelligence on {targetNation}. " +
                                        "Active research areas identified.";
                    report.Details.Add("Active research in 2-3 fields detected.");
                    report.Details.Add("Technology level estimated at equivalent to our tier " +
                                     $"{UnityEngine.Random.Range(0, 2)}.");
                    if (intel.DiscoveredTechs.Count > 0)
                    {
                        report.Details.Add($"Known technologies: {string.Join(", ", intel.DiscoveredTechs.Take(3))}.");
                    }
                    break;

                case IntelLevel.High:
                    report.Description = $"Detailed technology intelligence on {targetNation}. " +
                                        "Research progress and breakthroughs tracked.";
                    report.Details.Add("Active research projects identified with progress estimates.");
                    report.Details.Add($"Approximately {UnityEngine.Random.Range(5, 12)} technologies confirmed.");
                    report.Details.Add("Research facility locations identified.");
                    if (intel.DiscoveredTechs.Count > 0)
                    {
                        report.Details.Add($"Known technologies: {string.Join(", ", intel.DiscoveredTechs)}.");
                    }
                    break;

                case IntelLevel.Complete:
                    report.Description = $"Complete technology intelligence on {targetNation}. " +
                                        "Full research awareness achieved.";
                    report.Details.Add("All research projects tracked with exact progress percentages.");
                    report.Details.Add("Research priorities and allocation understood.");
                    report.Details.Add("Technology tree fully mapped.");
                    report.Details.Add("Upcoming breakthroughs predicted based on research trajectory.");
                    if (intel.DiscoveredTechs.Count > 0)
                    {
                        report.Details.Add($"Complete tech list: {string.Join(", ", intel.DiscoveredTechs)}.");
                    }
                    break;
            }

            _reportCooldowns[cooldownKey] = currentTurn;
            return report;
        }

        /// <summary>
        /// Generates a diplomatic intelligence report about the target nation,
        /// detailing alliances, tensions, and foreign policy direction.
        /// </summary>
        /// <param name="targetNation">The nation to report on.</param>
        /// <returns>A diplomatic IntelReport, or null if insufficient intel.</returns>
        public IntelReport GenerateDiplomaticReport(string targetNation)
        {
            if (_espionageManager == null)
                return null;

            NationIntel intel = _espionageManager.GetIntelForNation(targetNation);
            if (intel.DiplomaticIntel == IntelLevel.None)
                return null;

            string cooldownKey = $"{targetNation}_Diplomatic";
            int currentTurn = GetEstimatedTurnNumber();

            _reportIdCounter++;
            IntelReport report = new IntelReport(
                $"RPT_DIP_{_reportIdCounter:D4}",
                $"Diplomatic Intelligence: {targetNation}",
                "Intelligence Agency",
                targetNation,
                currentTurn
            )
            {
                Category = IntelReportCategory.Diplomatic,
                Confidence = intel.DiplomaticIntel
            };

            switch (intel.DiplomaticIntel)
            {
                case IntelLevel.Low:
                    report.Description = $"Limited diplomatic intelligence on {targetNation}.";
                    report.Details.Add("General diplomatic posture assessed as cautious.");
                    break;

                case IntelLevel.Medium:
                    report.Description = $"Moderate diplomatic intelligence on {targetNation}.";
                    report.Details.Add("Major alliances and rivalries identified.");
                    report.Details.Add("Diplomatic overtures to neighboring nations detected.");
                    break;

                case IntelLevel.High:
                    report.Description = $"Detailed diplomatic intelligence on {targetNation}.";
                    report.Details.Add("Treaty obligations and secret agreements partially uncovered.");
                    report.Details.Add("Ambassador network and diplomatic priorities understood.");
                    report.Details.Add("Trade negotiation positions estimated.");
                    break;

                case IntelLevel.Complete:
                    report.Description = $"Complete diplomatic intelligence on {targetNation}.";
                    report.Details.Add("All treaties, agreements, and obligations documented.");
                    report.Details.Add("Diplomatic strategy and long-term goals understood.");
                    report.Details.Add("Communication channels and back-channel negotiations monitored.");
                    break;
            }

            _reportCooldowns[cooldownKey] = currentTurn;
            return report;
        }

        // ====================================================================
        // PRIVATE HELPERS
        // ====================================================================

        /// <summary>
        /// Generates a report based on the available intel level, choosing the most
        /// informative category automatically.
        /// </summary>
        private IntelReport GenerateReportFromIntel(string sourceNation, string targetNation, NationIntel intel)
        {
            if (UnityEngine.Random.value > networkReportChance)
                return null;

            // Determine the strongest intel category to report on
            IntelLevel maxIntel = IntelLevel.None;
            IntelReportCategory bestCategory = IntelReportCategory.General;

            if (intel.MilitaryIntel > maxIntel)
            {
                maxIntel = intel.MilitaryIntel;
                bestCategory = IntelReportCategory.Military;
            }
            if (intel.EconomicIntel > maxIntel)
            {
                maxIntel = intel.EconomicIntel;
                bestCategory = IntelReportCategory.Economic;
            }
            if (intel.TechIntel > maxIntel)
            {
                maxIntel = intel.TechIntel;
                bestCategory = IntelReportCategory.Technology;
            }
            if (intel.DiplomaticIntel > maxIntel)
            {
                maxIntel = intel.DiplomaticIntel;
                bestCategory = IntelReportCategory.Diplomatic;
            }

            if (maxIntel == IntelLevel.None)
                return null;

            IntelReport report = null;

            // Add some randomness to category selection
            float categoryRoll = UnityEngine.Random.value;
            if (categoryRoll < 0.35f || bestCategory == IntelReportCategory.Military)
                report = GenerateMilitaryReport(targetNation, _hexGrid);
            else if (categoryRoll < 0.60f || bestCategory == IntelReportCategory.Economic)
                report = GenerateEconomicReport(targetNation);
            else if (categoryRoll < 0.80f || bestCategory == IntelReportCategory.Technology)
                report = GenerateTechReport(targetNation);
            else
                report = GenerateDiplomaticReport(targetNation);

            if (report != null)
            {
                report.SourceNation = sourceNation;
            }

            return report;
        }

        /// <summary>
        /// Stores a report and indexes it by receiving nation.
        /// Enforces maximum report count by archiving oldest reports.
        /// </summary>
        private void StoreReport(IntelReport report, string receivingNation)
        {
            _reports[report.ReportId] = report;

            if (!_reportsByNation.ContainsKey(receivingNation))
                _reportsByNation[receivingNation] = new List<string>();
            _reportsByNation[receivingNation].Add(report.ReportId);

            Debug.Log($"[IntelReportManager] New report: [{report.Category}] {report.Title} " +
                       $"(Confidence: {report.Confidence})");
            OnNewReportGenerated?.Invoke(report, receivingNation);

            // Enforce max report limit
            EnforceReportLimit();
        }

        /// <summary>
        /// Removes the oldest reports when the total count exceeds <see cref="maxStoredReports"/>.
        /// </summary>
        private void EnforceReportLimit()
        {
            if (_reports.Count <= maxStoredReports)
                return;

            var oldestReports = _reports.Values
                .OrderBy(r => r.TurnNumber)
                .Take(_reports.Count - maxStoredReports)
                .ToList();

            foreach (IntelReport old in oldestReports)
            {
                _reports.Remove(old.ReportId);
                foreach (var kvp in _reportsByNation)
                {
                    kvp.Value.Remove(old.ReportId);
                }
            }

            Debug.Log($"[IntelReportManager] Archived {oldestReports.Count} old reports (limit: {maxStoredReports}).");
        }

        /// <summary>
        /// Returns a random economic health descriptor for low-intel reports.
        /// </summary>
        private string GetRandomEconomicHealth()
        {
            string[] states = { "Struggling", "Stable", "Growing", "Declining", "Recovering" };
            return states[UnityEngine.Random.Range(0, states.Length)];
        }

        /// <summary>
        /// Returns a random technological era descriptor for low-intel reports.
        /// </summary>
        private string GetRandomTechEra()
        {
            string[] eras = { "Pre-Industrial", "Early Industrial", "Industrial", "Post-Industrial", "Advanced" };
            return eras[UnityEngine.Random.Range(0, eras.Length)];
        }

        /// <summary>
        /// Estimates the current turn number from the espionage manager's state.
        /// Falls back to a counter-based estimate if no manager is available.
        /// </summary>
        private int GetEstimatedTurnNumber()
        {
            // Use the report counter as a rough turn estimate when no turn manager is linked
            return _reportIdCounter > 0 ? (_reportIdCounter / 3) + 1 : 1;
        }

        /// <summary>
        /// Searches the scene for the EspionageManager instance.
        /// </summary>
        private EspionageManager FindEspionageManager()
        {
            // Try FindObjectOfType first (works if already in scene)
            var manager = FindAnyObjectByType<EspionageManager>();
            if (manager != null)
                return manager;

            // Fallback: search for GameManager and get component
            var gameManager = GameObject.Find("GameManager");
            return gameManager != null ? gameManager.GetComponent<EspionageManager>() : null;
        }

        /// <summary>
        /// Searches the scene for the HexGrid instance.
        /// </summary>
        private HexGrid FindHexGrid()
        {
            var grid = FindAnyObjectByType<HexGrid>();
            if (grid != null)
                return grid;

            var gridObj = GameObject.Find("HexGrid");
            return gridObj != null ? gridObj.GetComponent<HexGrid>() : null;
        }
    }
}
