// ============================================================================
// IRON PROTOCOL - Turn-Based Strategy Game
// File: GameConfig.cs
// Namespace: IronProtocol.Data
// Description: Main game configuration ScriptableObject. Defines map dimensions,
//              starting resources, victory conditions, difficulty, and gameplay
//              toggles. Accessible from any system via Inspector reference.
// ============================================================================

using UnityEngine;

namespace IronProtocol.Data
{
    /// <summary>
    /// Enumeration of supported victory conditions.
    /// </summary>
    public enum VictoryCondition
    {
        /// <summary>Control a majority of all territories on the map.</summary>
        Domination,

        /// <summary>Accumulate a treasury above the economic victory threshold.</summary>
        Economic,

        /// <summary>Form alliances with a majority of surviving nations.</summary>
        Diplomatic
    }

    /// <summary>
    /// Main game configuration ScriptableObject.
    /// Defines all global gameplay parameters including map dimensions, starting
    /// resources, economy settings, victory conditions, AI difficulty, and
    /// feature toggles. Create instances via the Assets menu:
    /// <para><c>Right-Click → Create → Iron Protocol → Game Config</c></para>
    /// </summary>
    [CreateAssetMenu(fileName = "NewGameConfig", menuName = "Iron Protocol/Game Config")]
    public class GameConfig : ScriptableObject
    {
        // ------------------------------------------------------------------
        // Map Configuration
        // ------------------------------------------------------------------

        [Header("Map Configuration")]
        [Tooltip("Width of the hex map in hex columns.")]
        [SerializeField] [Range(5, 50)] private int mapWidth = 20;

        [Tooltip("Height of the hex map in hex rows.")]
        [SerializeField] [Range(5, 40)] private int mapHeight = 15;

        [Tooltip("Size of each hex tile in world units.")]
        [SerializeField] [Range(0.5f, 3.0f)] private float hexSize = 1.0f;

        /// <summary>Width of the hex map in hex columns.</summary>
        public int MapWidth => mapWidth;

        /// <summary>Height of the hex map in hex rows.</summary>
        public int MapHeight => mapHeight;

        /// <summary>Size of each hex tile in world units.</summary>
        public float HexSize => hexSize;

        // ------------------------------------------------------------------
        // Economy Configuration
        // ------------------------------------------------------------------

        [Header("Economy")]
        [Tooltip("Starting treasury amount for each nation.")]
        [SerializeField] private int startingTreasury = 1000;

        [Tooltip("Base income generated by each city per turn.")]
        [SerializeField] private int cityIncomeBase = 50;

        [Tooltip("Percentage growth rate for city income per turn (0.05 = 5%).")]
        [SerializeField] [Range(0f, 0.2f)] private float incomeGrowthRate = 0.05f;

        /// <summary>Starting treasury amount for each nation.</summary>
        public int StartingTreasury => startingTreasury;

        /// <summary>Base income generated by each city per turn.</summary>
        public int CityIncomeBase => cityIncomeBase;

        /// <summary>Percentage growth rate for city income per turn (e.g. 0.05 = 5%).</summary>
        public float IncomeGrowthRate => incomeGrowthRate;

        // ------------------------------------------------------------------
        // Victory Configuration
        // ------------------------------------------------------------------

        [Header("Victory")]
        [Tooltip("The victory condition for this game session.")]
        [SerializeField] private VictoryCondition victoryCondition = VictoryCondition.Domination;

        [Tooltip("Number of turns after which the game ends and scores are tallied.")]
        [SerializeField] [Range(10, 500)] private int turnsToWin = 100;

        /// <summary>The victory condition for this game session.</summary>
        public VictoryCondition VictoryConditionType => victoryCondition;

        /// <summary>Number of turns after which the game ends and scores are tallied.</summary>
        public int TurnsToWin => turnsToWin;

        // ------------------------------------------------------------------
        // AI Configuration
        // ------------------------------------------------------------------

        [Header("AI")]
        [Tooltip("AI difficulty level (0.0 = easiest, 1.0 = hardest). Affects decision quality and resource bonuses.")]
        [SerializeField] [Range(0f, 1f)] private float aiDifficulty = 0.7f;

        /// <summary>AI difficulty level (0.0 = easiest, 1.0 = hardest).</summary>
        public float AIDifficulty => aiDifficulty;

        // ------------------------------------------------------------------
        // Feature Toggles
        // ------------------------------------------------------------------

        [Header("Features")]
        [Tooltip("Enable dynamic weather system that changes each turn.")]
        [SerializeField] private bool dynamicWeather = true;

        [Tooltip("Enable the resource market with dynamic pricing.")]
        [SerializeField] private bool enableMarket = true;

        /// <summary>Whether dynamic weather is enabled.</summary>
        public bool DynamicWeather => dynamicWeather;

        /// <summary>Whether the resource market is enabled.</summary>
        public bool EnableMarket => enableMarket;

        // ------------------------------------------------------------------
        // Advanced Settings
        // ------------------------------------------------------------------

        [Header("Advanced")]
        [Tooltip("Maximum number of units per nation (0 = unlimited).")]
        [SerializeField] [Range(0, 200)] private int maxUnitsPerNation = 50;

        [Tooltip("Base movement points for all units (can be overridden per unit type).")]
        [SerializeField] [Range(1, 10)] private int baseMovementPoints = 2;

        [Tooltip("Combat randomness factor (0 = deterministic, 1 = fully random).")]
        [SerializeField] [Range(0f, 1f)] private float combatRandomness = 0.15f;

        [Tooltip("Fortification defense bonus (0.0 = no bonus, 1.0 = double defense).")]
        [SerializeField] [Range(0f, 1f)] private float fortificationBonus = 0.3f;

        /// <summary>Maximum number of units per nation (0 = unlimited).</summary>
        public int MaxUnitsPerNation => maxUnitsPerNation;

        /// <summary>Base movement points for all units.</summary>
        public int BaseMovementPoints => baseMovementPoints;

        /// <summary>Combat randomness factor (0 = deterministic, 1 = fully random).</summary>
        public float CombatRandomness => combatRandomness;

        /// <summary>Fortification defense bonus multiplier.</summary>
        public float FortificationBonus => fortificationBonus;

        // ------------------------------------------------------------------
        // Validation
        // ------------------------------------------------------------------

        private void OnValidate()
        {
            // Ensure positive values
            mapWidth = Mathf.Max(5, mapWidth);
            mapHeight = Mathf.Max(5, mapHeight);
            hexSize = Mathf.Max(0.5f, hexSize);
            startingTreasury = Mathf.Max(0, startingTreasury);
            cityIncomeBase = Mathf.Max(0, cityIncomeBase);
            incomeGrowthRate = Mathf.Clamp(incomeGrowthRate, 0f, 0.5f);
            turnsToWin = Mathf.Max(1, turnsToWin);
            aiDifficulty = Mathf.Clamp01(aiDifficulty);
            combatRandomness = Mathf.Clamp01(combatRandomness);
            fortificationBonus = Mathf.Clamp(fortificationBonus, 0f, 1f);
        }

        /// <summary>
        /// Returns a human-readable summary of the configuration.
        /// </summary>
        public override string ToString()
        {
            return $"GameConfig: {mapWidth}x{mapHeight} map, {hexSize} hex size, " +
                   $"Treasury: {startingTreasury}, Income: {cityIncomeBase} (+{incomeGrowthRate:P0}/turn), " +
                   $"Victory: {victoryCondition} in {turnsToWin} turns, " +
                   $"AI: {aiDifficulty:P0}, Weather: {dynamicWeather}, Market: {enableMarket}";
        }
    }
}
